spring:
  sql:
    init:
      mode: always

  application:
    name: YiMo
  datasource:
    url: jdbc:h2:tcp://localhost:9092/./data/YiMo
    driver-class-name: org.h2.Driver
    username: sa
    password: YiMo
  h2:
    console:
      enabled: true

# 服务器配置
server:
  port: 8081
  # servlet:

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true